//! Read/write `connectors.env` (Telegram, Slack, Discord activation + non-secret config).

use akasha_vault::Vault;
use std::collections::HashMap;
use std::path::Path;

/// Known connector env keys exposed in settings UI.
pub const CONNECTOR_KEYS: &[(&str, &str)] = &[
    ("telegram", "AKASHA_TELEGRAM_ENABLED"),
    ("slack", "AKASHA_SLACK_ENABLED"),
    ("discord", "AKASHA_DISCORD_ENABLED"),
];

/// Non-secret env keys stored in connectors.env.
pub const CONNECTOR_ENV_CONFIG_KEYS: &[&str] = &["AKASHA_TELEGRAM_NOTIFY_CHAT_ID"];

/// Vault keys for connector secrets (never returned in API responses).
pub const CONNECTOR_VAULT_KEYS: &[&str] = &[
    "telegram_bot_token",
    "slack_signing_secret",
    "discord_bot_token",
];

fn env_enabled(value: Option<&str>) -> bool {
    value.map(|v| v.trim() == "1").unwrap_or(false)
}

fn read_env_file(data_dir: &Path) -> HashMap<String, String> {
    let path = data_dir.join("connectors.env");
    if !path.is_file() {
        return HashMap::new();
    }
    let content = std::fs::read_to_string(&path).unwrap_or_default();
    akasha_core::env_file::parse_env_file_content(&content).0
}

fn write_env_file(data_dir: &Path, lines: &[String]) -> anyhow::Result<()> {
    let path = data_dir.join("connectors.env");
    std::fs::write(path, lines.join("\n"))?;
    Ok(())
}

fn load_or_init_lines(data_dir: &Path) -> Vec<String> {
    let path = data_dir.join("connectors.env");
    if path.exists() {
        std::fs::read_to_string(&path)
            .unwrap_or_default()
            .lines()
            .map(String::from)
            .collect()
    } else {
        vec![
            "# Connectors activation (generated by Akasha settings)".to_string(),
            "# Set AKASHA_*_ENABLED=1 to enable; secrets go in vault".to_string(),
            String::new(),
        ]
    }
}

fn upsert_env_line(lines: &mut Vec<String>, key: &str, value: &str) {
    let new_line = format!("{}={}", key, value);
    for line in lines.iter_mut() {
        let trimmed = line.trim();
        if trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }
        if let Some((k, _)) = trimmed.split_once('=') {
            if k.trim() == key {
                *line = new_line.clone();
                return;
            }
        }
    }
    lines.push(new_line);
}

fn remove_env_line(lines: &mut Vec<String>, key: &str) {
    lines.retain(|line| {
        let trimmed = line.trim();
        if trimmed.starts_with('#') || trimmed.is_empty() {
            return true;
        }
        trimmed
            .split_once('=')
            .map(|(k, _)| k.trim() != key)
            .unwrap_or(true)
    });
}

/// One connector row for GET /api/connectors.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ConnectorStatus {
    pub id: &'static str,
    pub env_key: &'static str,
    pub enabled_in_file: bool,
    pub active_in_process: bool,
}

/// Non-secret connector configuration + vault presence flags (no secret values).
#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct ConnectorsConfigView {
    pub telegram_notify_chat_id: Option<String>,
    pub telegram_token_configured: bool,
    pub slack_signing_secret_configured: bool,
    pub discord_token_configured: bool,
}

/// Payload for POST /api/connectors (optional fields = leave unchanged).
#[derive(Debug, Clone, Default, serde::Deserialize)]
pub struct ConnectorsUpdate {
    #[serde(default)]
    pub telegram: Option<bool>,
    #[serde(default)]
    pub slack: Option<bool>,
    #[serde(default)]
    pub discord: Option<bool>,
    #[serde(default)]
    pub telegram_notify_chat_id: Option<String>,
    /// Set vault secret; empty string ignored (keep existing).
    #[serde(default)]
    pub telegram_bot_token: Option<String>,
    #[serde(default)]
    pub slack_signing_secret: Option<String>,
    #[serde(default)]
    pub discord_bot_token: Option<String>,
}

pub fn connectors_config_view(data_dir: &Path) -> ConnectorsConfigView {
    let file_map = read_env_file(data_dir);
    let vault_keys: std::collections::HashSet<String> = akasha_vault::open_vault(data_dir)
        .ok()
        .and_then(|v| v.list_keys().ok())
        .unwrap_or_default()
        .into_iter()
        .collect();

    ConnectorsConfigView {
        telegram_notify_chat_id: file_map
            .get("AKASHA_TELEGRAM_NOTIFY_CHAT_ID")
            .cloned()
            .filter(|s| !s.trim().is_empty()),
        telegram_token_configured: vault_keys.contains("telegram_bot_token"),
        slack_signing_secret_configured: vault_keys.contains("slack_signing_secret"),
        discord_token_configured: vault_keys.contains("discord_bot_token"),
    }
}

/// Read connector flags from disk and compare with current process env.
pub fn connectors_status(data_dir: &Path) -> Vec<ConnectorStatus> {
    let file_map = read_env_file(data_dir);

    CONNECTOR_KEYS
        .iter()
        .map(|(id, key)| {
            let file_val = file_map.get(*key).map(String::as_str);
            let enabled_in_file = env_enabled(file_val);
            let active_in_process = env_enabled(std::env::var(key).ok().as_deref());
            ConnectorStatus {
                id,
                env_key: key,
                enabled_in_file,
                active_in_process,
            }
        })
        .collect()
}

/// Update connector enable flags in connectors.env, preserving comments and unrelated lines.
pub fn write_connectors_enabled(
    data_dir: &Path,
    telegram: bool,
    slack: bool,
    discord: bool,
) -> anyhow::Result<()> {
    let mut lines = load_or_init_lines(data_dir);
    for (key, enabled) in [
        ("AKASHA_TELEGRAM_ENABLED", telegram),
        ("AKASHA_SLACK_ENABLED", slack),
        ("AKASHA_DISCORD_ENABLED", discord),
    ] {
        upsert_env_line(&mut lines, key, if enabled { "1" } else { "0" });
    }
    write_env_file(data_dir, &lines)
}

fn set_vault_if_non_empty(data_dir: &Path, key: &str, value: Option<&str>) -> anyhow::Result<()> {
    let Some(v) = value else { return Ok(()) };
    let trimmed = v.trim();
    if trimmed.is_empty() {
        return Ok(());
    }
    if !CONNECTOR_VAULT_KEYS.contains(&key) {
        anyhow::bail!("vault key not allowed: {key}");
    }
    let vault = akasha_vault::open_vault(data_dir)?;
    vault.set(key, trimmed)?;
    Ok(())
}

/// Apply full connector update: flags, env config, vault secrets.
pub fn apply_connectors_update(data_dir: &Path, update: &ConnectorsUpdate) -> anyhow::Result<()> {
    let current = connectors_status(data_dir);
    let telegram = update.telegram.unwrap_or_else(|| {
        current
            .iter()
            .find(|c| c.id == "telegram")
            .map(|c| c.enabled_in_file)
            .unwrap_or(false)
    });
    let slack = update.slack.unwrap_or_else(|| {
        current
            .iter()
            .find(|c| c.id == "slack")
            .map(|c| c.enabled_in_file)
            .unwrap_or(false)
    });
    let discord = update.discord.unwrap_or_else(|| {
        current
            .iter()
            .find(|c| c.id == "discord")
            .map(|c| c.enabled_in_file)
            .unwrap_or(false)
    });

    let mut lines = load_or_init_lines(data_dir);
    for (key, enabled) in [
        ("AKASHA_TELEGRAM_ENABLED", telegram),
        ("AKASHA_SLACK_ENABLED", slack),
        ("AKASHA_DISCORD_ENABLED", discord),
    ] {
        upsert_env_line(&mut lines, key, if enabled { "1" } else { "0" });
    }

    if let Some(ref chat_id) = update.telegram_notify_chat_id {
        let t = chat_id.trim();
        if t.is_empty() {
            remove_env_line(&mut lines, "AKASHA_TELEGRAM_NOTIFY_CHAT_ID");
        } else {
            upsert_env_line(&mut lines, "AKASHA_TELEGRAM_NOTIFY_CHAT_ID", t);
        }
    }

    write_env_file(data_dir, &lines)?;

    set_vault_if_non_empty(
        data_dir,
        "telegram_bot_token",
        update.telegram_bot_token.as_deref(),
    )?;
    set_vault_if_non_empty(
        data_dir,
        "slack_signing_secret",
        update.slack_signing_secret.as_deref(),
    )?;
    set_vault_if_non_empty(
        data_dir,
        "discord_bot_token",
        update.discord_bot_token.as_deref(),
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn write_connectors_creates_and_updates_file() {
        let dir = tempfile::tempdir().unwrap();
        write_connectors_enabled(dir.path(), true, false, true).unwrap();
        let content = fs::read_to_string(dir.path().join("connectors.env")).unwrap();
        assert!(content.contains("AKASHA_TELEGRAM_ENABLED=1"));
        assert!(content.contains("AKASHA_SLACK_ENABLED=0"));
        assert!(content.contains("AKASHA_DISCORD_ENABLED=1"));
    }

    #[test]
    fn connectors_status_reads_file_flags() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(
            dir.path().join("connectors.env"),
            "AKASHA_TELEGRAM_ENABLED=1\nAKASHA_SLACK_ENABLED=0\n",
        )
        .unwrap();
        let status = connectors_status(dir.path());
        let tg = status.iter().find(|s| s.id == "telegram").unwrap();
        assert!(tg.enabled_in_file);
    }

    #[test]
    fn apply_update_sets_notify_chat_id() {
        let dir = tempfile::tempdir().unwrap();
        apply_connectors_update(
            dir.path(),
            &ConnectorsUpdate {
                telegram: Some(true),
                telegram_notify_chat_id: Some("12345".into()),
                ..Default::default()
            },
        )
        .unwrap();
        let map = read_env_file(dir.path());
        assert_eq!(map.get("AKASHA_TELEGRAM_NOTIFY_CHAT_ID").map(String::as_str), Some("12345"));
    }
}
