//! Provider trait and implementations (Ollama, Akasha Core, OpenAI, OpenRouter).

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::time::Duration;
use tracing::warn;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    pub prompt: String,
    pub max_tokens: Option<u32>,
    pub temperature: Option<f32>,
    /// Nucleus sampling: probability mass to sample from (0.0-1.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,
    /// Top-k sampling: only sample from top k tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<u32>,
    /// Frequency penalty (OpenAI): penalize repeated tokens. Range: -2.0 to 2.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency_penalty: Option<f32>,
    /// Presence penalty (OpenAI): penalize new tokens. Range: -2.0 to 2.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub presence_penalty: Option<f32>,
    /// Repeat penalty (Ollama/local): 1.0 = no penalty, > 1.0 = penalize repetition.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub repeat_penalty: Option<f32>,
    /// Context window size (local providers like Ollama).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_ctx: Option<u32>,
    /// Number of GPU layers (local providers like Ollama).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_gpu: Option<u32>,
    /// Model thinking/reasoning effort level when supported by provider/model.
    /// Expected values: off, low, medium, high.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_level: Option<String>,
    /// When set, router uses this task type instead of classifying from the prompt (e.g. "system" for memory extraction, decomposition).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preferred_task_type: Option<String>,
    /// Optional system message (identity, personality, rules). When set, providers that support it send it as system role; others concatenate with prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    /// Optional image data URLs (data:image/png;base64,...) for vision-capable providers; appended to user message content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_data_urls: Option<Vec<String>>,
}

fn normalized_thinking_level(level: Option<&str>) -> Option<&'static str> {
    match level.map(|s| s.trim().to_ascii_lowercase()) {
        Some(s) if s == "off" || s == "none" || s == "disabled" => Some("off"),
        Some(s) if s == "low" => Some("low"),
        Some(s) if s == "medium" || s == "med" => Some("medium"),
        Some(s) if s == "high" => Some("high"),
        _ => None,
    }
}

fn ollama_think_enabled(level: Option<&str>) -> Option<bool> {
    // Ollama currently exposes a boolean `think` switch (not a graded budget).
    // We map levels conservatively to reduce runaway reasoning-only outputs:
    // - off/low -> false
    // - medium/high -> true
    match normalized_thinking_level(level) {
        Some("off") => Some(false),
        Some("low") => Some(false),
        Some("medium") | Some("high") => Some(true),
        _ => None,
    }
}

fn supports_openai_reasoning_effort(model: &str) -> bool {
    let m = model.to_ascii_lowercase();
    m.starts_with("o1")
        || m.starts_with("o3")
        || m.starts_with("o4")
        || m.contains("gpt-5")
}

fn anthropic_thinking_budget_tokens(level: &str) -> Option<u32> {
    match level {
        "low" => Some(1024),
        "medium" => Some(4096),
        "high" => Some(8192),
        _ => None,
    }
}

fn supports_anthropic_thinking(model: &str) -> bool {
    let m = model.to_ascii_lowercase();
    m.contains("claude-3-7") || m.contains("claude-sonnet-4")
}

fn supports_google_thinking(model: &str) -> bool {
    let m = model.to_ascii_lowercase();
    m.contains("gemini-2.5")
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    pub text: String,
    pub usage: Option<TokenUsage>,
    pub model_used: String,
    /// Cost in USD for this call (set by router/fallback when available).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
    /// Thinking/reasoning process from the model (e.g. extended thinking).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,
    /// Reason why model stopped (e.g. "length", "stop_token", null = completed gracefully).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub done_reason: Option<String>,
    /// Number of tokens generated by the model (may differ from usage.completion_tokens).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eval_count: Option<u64>,
    /// Total duration in nanoseconds (useful for performance analysis).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_duration_ns: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
}

#[async_trait]
pub trait LLMProvider: Send + Sync {
    fn name(&self) -> &str;
    fn is_available(&self) -> bool;
    fn is_local(&self) -> bool {
        false
    }
    /// Whether this provider can stream chunks (avoids total timeout; use idle timeout instead).
    fn supports_streaming(&self) -> bool {
        false
    }
    /// Complete with optional model override from routing config (e.g. "llama3.2", "codellama").
    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError>;
    /// Complete and send each chunk to `chunk_tx`. Default: call `complete()` and send full text once.
    async fn complete_stream(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
        chunk_tx: std::sync::mpsc::Sender<String>,
    ) -> Result<CompletionResponse, ProviderError> {
        let response = self.complete(request, timeout, model_override).await?;
        let _ = chunk_tx.send(response.text.clone());
        Ok(response)
    }
    fn get_cost(&self, _usage: &TokenUsage) -> f64 {
        0.0
    }
}

#[derive(Debug, thiserror::Error)]
pub enum ProviderError {
    #[error("timeout (HTTP request deadline exceeded; logs should include base_url, model, timeout_secs)")]
    Timeout,
    #[error("api error: {0}")]
    Api(String),
    #[error("rate limit")]
    RateLimit,
    #[error("unavailable")]
    Unavailable,
    #[error("auth: {0}")]
    Auth(String),
}

// --- Ollama (local)
pub struct OllamaProvider {
    base_url: String,
}

impl OllamaProvider {
    pub fn new(base_url: Option<String>) -> Self {
        Self {
            base_url: base_url.unwrap_or_else(|| "http://localhost:11434".into()),
        }
    }

    async fn complete_async(
        &self,
        request: &CompletionRequest,
        model: &str,
        timeout: Duration,
    ) -> Result<CompletionResponse, ProviderError> {
        let client = reqwest::Client::new();
        let url = format!("{}/api/generate", self.base_url);
        let prompt = match &request.system_prompt {
            Some(s) if !s.is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
            _ => request.prompt.clone(),
        };

        // Build options with all supported parameters (Ollama-compatible).
        let mut options = serde_json::json!({
            "num_predict": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7),
        });

        if let Some(top_p) = request.top_p {
            options["top_p"] = serde_json::json!(top_p);
        }
        if let Some(top_k) = request.top_k {
            options["top_k"] = serde_json::json!(top_k);
        }
        if let Some(repeat_penalty) = request.repeat_penalty {
            options["repeat_penalty"] = serde_json::json!(repeat_penalty);
        }
        if let Some(num_ctx) = request.num_ctx {
            options["num_ctx"] = serde_json::json!(num_ctx);
        }
        if let Some(num_gpu) = request.num_gpu {
            options["num_gpu"] = serde_json::json!(num_gpu);
        }

        let body = serde_json::json!({
            "model": model,
            "prompt": prompt,
            "stream": false,
            "options": options
        });
        let mut body = body;
        if let Some(enabled) = ollama_think_enabled(request.thinking_level.as_deref()) {
            // Ollama supports `think` as a boolean toggle.
            body["think"] = serde_json::json!(enabled);
        }
        let resp = client
            .post(&url)
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    warn!(
                        provider = "ollama",
                        base_url = %self.base_url,
                        endpoint = %url,
                        model = %model,
                        timeout_secs = timeout.as_secs(),
                        prompt_chars = prompt.chars().count(),
                        reqwest_error = %e,
                        "Ollama request timed out (reqwest total deadline: cold model load, slow generation, or unreachable host often exceed this; check network and llm_router timeout_per_call)"
                    );
                    ProviderError::Timeout
                } else {
                    ProviderError::Api(e.to_string())
                }
            })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if !resp.status().is_success() {
            return Err(ProviderError::Api(format!("status {}", resp.status())));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| {
            if e.is_timeout() {
                warn!(
                    provider = "ollama",
                    base_url = %self.base_url,
                    endpoint = %url,
                    model = %model,
                    timeout_secs = timeout.as_secs(),
                    phase = "read_body",
                    reqwest_error = %e,
                    "Ollama response body read timed out (same total deadline as send; very large JSON or slow link)"
                );
                ProviderError::Timeout
            } else {
                ProviderError::Api(e.to_string())
            }
        })?;
        let text = json.get("response").and_then(|v| v.as_str()).unwrap_or("").to_string();
        if text.trim().is_empty() {
            let full = serde_json::to_string_pretty(&json).unwrap_or_else(|_| json.to_string());
            warn!(
                model = %model,
                "Ollama returned empty text. Full API response (for --foreground debug):\n{}",
                full
            );
        }
        let usage = json.get("eval_count").and_then(|v| v.as_u64()).map(|c| TokenUsage {
            prompt_tokens: 0,
            completion_tokens: c,
        });

        // Extract model metadata for debugging
        let thinking = json.get("thinking").and_then(|v| v.as_str()).map(String::from);
        let done_reason = json.get("done_reason").and_then(|v| v.as_str()).map(String::from);
        let eval_count = json.get("eval_count").and_then(|v| v.as_u64());
        let total_duration_ns = json.get("total_duration").and_then(|v| v.as_u64());

        // Log if truncated (done_reason = "length")
        if done_reason.as_deref() == Some("length") {
            warn!(
                model = %model,
                text_len = text.len(),
                thinking_len = thinking.as_ref().map(|t| t.len()),
                eval_count = ?eval_count,
                "Model response truncated due to max_tokens limit"
            );
        }

        Ok(CompletionResponse {
            text,
            usage,
            model_used: model.to_string(),
            cost_usd: None,
            thinking,
            done_reason,
            eval_count,
            total_duration_ns,
        })
    }
}

#[async_trait]
impl LLMProvider for OllamaProvider {
    fn name(&self) -> &str {
        "ollama"
    }

    fn is_available(&self) -> bool {
        let client = reqwest::blocking::Client::builder()
            .timeout(Duration::from_secs(2))
            .build()
            .unwrap();
        client.get(format!("{}/api/tags", self.base_url)).send().is_ok()
    }

    fn is_local(&self) -> bool {
        true
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        let model = model_override.unwrap_or("llama3.2");
        self.complete_async(request, model, timeout).await
    }
}

// --- OpenAI (cloud)
pub struct OpenAIProvider {
    api_key: String,
    base_url: String,
}

impl OpenAIProvider {
    pub fn new(api_key: Option<String>, base_url: Option<String>) -> Self {
        Self {
            api_key: api_key.unwrap_or_default(),
            base_url: base_url
                .unwrap_or_else(|| "https://api.openai.com/v1".into())
                .trim_end_matches('/')
                .to_string(),
        }
    }

    async fn complete_async(
        &self,
        request: &CompletionRequest,
        model: &str,
        timeout: Duration,
    ) -> Result<CompletionResponse, ProviderError> {
        if self.api_key.is_empty() {
            return Err(ProviderError::Auth("missing API key".into()));
        }
        let client = reqwest::Client::new();
        let url = format!("{}/chat/completions", self.base_url);
        let user_content = match &request.image_data_urls {
            Some(urls) if !urls.is_empty() => {
                let mut content = vec![serde_json::json!({ "type": "text", "text": request.prompt })];
                for url in urls {
                    content.push(serde_json::json!({
                        "type": "image_url",
                        "image_url": { "url": url }
                    }));
                }
                serde_json::Value::Array(content)
            }
            _ => serde_json::json!(request.prompt),
        };
        let messages = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => serde_json::json!([
                { "role": "system", "content": s.trim_end() },
                { "role": "user", "content": user_content }
            ]),
            _ => serde_json::json!([{ "role": "user", "content": user_content }]),
        };

        // Build request body with all supported OpenAI parameters.
        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7)
        });

        if let Some(top_p) = request.top_p {
            body["top_p"] = serde_json::json!(top_p);
        }
        if let Some(freq_penalty) = request.frequency_penalty {
            body["frequency_penalty"] = serde_json::json!(freq_penalty);
        }
        if let Some(pres_penalty) = request.presence_penalty {
            body["presence_penalty"] = serde_json::json!(pres_penalty);
        }
        if let Some(level) = normalized_thinking_level(request.thinking_level.as_deref()) {
            if level != "off" && supports_openai_reasoning_effort(model) {
                body["reasoning_effort"] = serde_json::json!(level);
            }
        }

        let resp = client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.api_key))
            .header("Content-Type", "application/json")
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    ProviderError::Timeout
                } else {
                    ProviderError::Api(e.to_string())
                }
            })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if resp.status().as_u16() == 401 {
            return Err(ProviderError::Auth("invalid API key".into()));
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("choices")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usage").map(|u| TokenUsage {
            prompt_tokens: u.get("prompt_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("completion_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        let model_used = json.get("model").and_then(|v| v.as_str()).unwrap_or(model).to_string();
        Ok(CompletionResponse {
            text,
            usage,
            model_used,
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

#[async_trait]
impl LLMProvider for OpenAIProvider {
    fn name(&self) -> &str {
        "openai"
    }

    fn is_available(&self) -> bool {
        !self.api_key.is_empty()
    }

    fn is_local(&self) -> bool {
        false
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        let model = model_override.unwrap_or("gpt-4o-mini");
        self.complete_async(request, model, timeout).await
    }

    fn get_cost(&self, usage: &TokenUsage) -> f64 {
        // Approx gpt-4o-mini: $0.15/1M input, $0.60/1M output (simplified)
        (usage.prompt_tokens as f64 * 0.15 + usage.completion_tokens as f64 * 0.60) / 1_000_000.0
    }
}

// --- OpenRouter (cloud, unified API compatible with OpenAI format)
pub struct OpenRouterProvider {
    api_key: String,
    base_url: String,
    /// HTTP-Referer header (optional; from config or OPENROUTER_SITE_URL env; default https://Akasha.local).
    site_url: Option<String>,
    /// X-Title header (optional; from config or OPENROUTER_APP_TITLE env; default Akasha).
    app_title: Option<String>,
}

impl OpenRouterProvider {
    pub fn new(
        api_key: Option<String>,
        base_url: Option<String>,
        site_url: Option<String>,
        app_title: Option<String>,
    ) -> Self {
        let site_url = site_url
            .filter(|s| !s.is_empty())
            .or_else(|| std::env::var("OPENROUTER_SITE_URL").ok().filter(|s| !s.is_empty()))
            .or_else(|| Some("https://Akasha.local".into()));
        let app_title = app_title
            .filter(|s| !s.is_empty())
            .or_else(|| std::env::var("OPENROUTER_APP_TITLE").ok().filter(|s| !s.is_empty()))
            .or_else(|| Some("Akasha".into()));
        Self {
            api_key: api_key.unwrap_or_default(),
            base_url: base_url
                .unwrap_or_else(|| "https://openrouter.ai/api/v1".into())
                .trim_end_matches('/')
                .to_string(),
            site_url,
            app_title,
        }
    }
}

#[async_trait]
impl LLMProvider for OpenRouterProvider {
    fn name(&self) -> &str {
        "openrouter"
    }

    fn is_available(&self) -> bool {
        !self.api_key.is_empty()
    }

    fn is_local(&self) -> bool {
        false
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        if self.api_key.is_empty() {
            return Err(ProviderError::Auth("missing API key".into()));
        }
        let model = model_override.unwrap_or("openai/gpt-4o-mini");
        let client = reqwest::Client::new();
        let url = format!("{}/chat/completions", self.base_url);
        let user_content = match &request.image_data_urls {
            Some(urls) if !urls.is_empty() => {
                let mut content = vec![serde_json::json!({ "type": "text", "text": request.prompt })];
                for url in urls {
                    content.push(serde_json::json!({
                        "type": "image_url",
                        "image_url": { "url": url }
                    }));
                }
                serde_json::Value::Array(content)
            }
            _ => serde_json::json!(request.prompt),
        };
        let messages = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => serde_json::json!([
                { "role": "system", "content": s.trim_end() },
                { "role": "user", "content": user_content }
            ]),
            _ => serde_json::json!([{ "role": "user", "content": user_content }]),
        };

        // Build request body with all supported OpenAI/OpenRouter parameters.
        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7)
        });

        if let Some(top_p) = request.top_p {
            body["top_p"] = serde_json::json!(top_p);
        }
        if let Some(freq_penalty) = request.frequency_penalty {
            body["frequency_penalty"] = serde_json::json!(freq_penalty);
        }
        if let Some(pres_penalty) = request.presence_penalty {
            body["presence_penalty"] = serde_json::json!(pres_penalty);
        }
        if let Some(level) = normalized_thinking_level(request.thinking_level.as_deref()) {
            if level != "off" && supports_openai_reasoning_effort(model) {
                body["reasoning_effort"] = serde_json::json!(level);
            }
        }

        let mut req = client
            .post(&url)
            .header("Authorization", format!("Bearer {}", self.api_key))
            .header("Content-Type", "application/json");
        let referer = self.site_url.as_deref().unwrap_or("https://Akasha.local");
        let title = self.app_title.as_deref().unwrap_or("Akasha");
        req = req
            .header("HTTP-Referer", referer)
            .header("X-Title", title);
        let resp = req
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    ProviderError::Timeout
                } else {
                    ProviderError::Api(e.to_string())
                }
            })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if resp.status().as_u16() == 401 {
            return Err(ProviderError::Auth("invalid API key".into()));
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        // Reject huge response bodies to avoid OOM (e.g. buggy API returning Content-Length: 31GB).
        const MAX_RESPONSE_BODY: u64 = 10 * 1024 * 1024; // 10 MiB
        if let Some(len) = resp.content_length() {
            if len > MAX_RESPONSE_BODY {
                return Err(ProviderError::Api(format!(
                    "LLM response body too large: {} bytes (max {}). Refusing to allocate.",
                    len, MAX_RESPONSE_BODY
                )));
            }
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("choices")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usage").map(|u| TokenUsage {
            prompt_tokens: u.get("prompt_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("completion_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        let model_used = json.get("model").and_then(|v| v.as_str()).unwrap_or(model).to_string();
        Ok(CompletionResponse {
            text,
            usage,
            model_used,
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

// --- Anthropic (cloud, Messages API)
pub struct AnthropicProvider {
    api_key: String,
    base_url: String,
}

impl AnthropicProvider {
    pub fn new(api_key: Option<String>, base_url: Option<String>) -> Self {
        Self {
            api_key: api_key.unwrap_or_default(),
            base_url: base_url
                .unwrap_or_else(|| "https://api.anthropic.com".into())
                .trim_end_matches('/')
                .to_string(),
        }
    }
}

#[async_trait]
impl LLMProvider for AnthropicProvider {
    fn name(&self) -> &str {
        "anthropic"
    }
    fn is_available(&self) -> bool {
        !self.api_key.is_empty()
    }
    fn is_local(&self) -> bool {
        false
    }
    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        if self.api_key.is_empty() {
            return Err(ProviderError::Auth("missing API key".into()));
        }
        let model = model_override.unwrap_or("claude-3-5-sonnet-20241022");
        let client = reqwest::Client::new();
        let url = format!("{}/v1/messages", self.base_url);
        let prompt = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
            _ => request.prompt.clone(),
        };
        let body = serde_json::json!({
            "model": model,
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "messages": [{ "role": "user", "content": prompt }]
        });
        let mut body = body;
        if let Some(level) = normalized_thinking_level(request.thinking_level.as_deref()) {
            if level != "off" && supports_anthropic_thinking(model) {
                if let Some(budget_tokens) = anthropic_thinking_budget_tokens(level) {
                    body["thinking"] = serde_json::json!({
                        "type": "enabled",
                        "budget_tokens": budget_tokens
                    });
                }
            }
        }
        let resp = client
            .post(&url)
            .header("x-api-key", &self.api_key)
            .header("anthropic-version", "2023-06-01")
            .header("Content-Type", "application/json")
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| if e.is_timeout() { ProviderError::Timeout } else { ProviderError::Api(e.to_string()) })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if resp.status().as_u16() == 401 {
            return Err(ProviderError::Auth("invalid API key".into()));
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("content")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|b| b.get("text"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usage").map(|u| TokenUsage {
            prompt_tokens: u.get("input_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("output_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        Ok(CompletionResponse {
            text,
            usage,
            model_used: model.to_string(),
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

// --- Azure OpenAI (cloud, same shape as OpenAI but custom endpoint + api-key header)
pub struct AzureOpenAIProvider {
    api_key: String,
    base_url: String,
}

impl AzureOpenAIProvider {
    pub fn new(api_key: Option<String>, base_url: Option<String>) -> Self {
        let base = base_url
            .unwrap_or_else(|| "https://your-resource.openai.azure.com".into())
            .trim_end_matches('/')
            .to_string();
        Self {
            api_key: api_key.unwrap_or_default(),
            base_url: base,
        }
    }
}

#[async_trait]
impl LLMProvider for AzureOpenAIProvider {
    fn name(&self) -> &str {
        "azure_openai"
    }
    fn is_available(&self) -> bool {
        !self.api_key.is_empty() && !self.base_url.is_empty()
    }
    fn is_local(&self) -> bool {
        false
    }
    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        if self.api_key.is_empty() {
            return Err(ProviderError::Auth("missing API key".into()));
        }
        let deployment = model_override.unwrap_or("gpt-4o-mini");
        let client = reqwest::Client::new();
        let url = format!(
            "{}/openai/deployments/{}/chat/completions?api-version=2024-02-15-preview",
            self.base_url.trim_end_matches('/'),
            deployment
        );
        let messages = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => serde_json::json!([
                { "role": "system", "content": s.trim_end() },
                { "role": "user", "content": request.prompt }
            ]),
            _ => serde_json::json!([{ "role": "user", "content": request.prompt }]),
        };

        // Build request body with OpenAI-compatible parameters.
        let mut body = serde_json::json!({
            "messages": messages,
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7)
        });

        if let Some(top_p) = request.top_p {
            body["top_p"] = serde_json::json!(top_p);
        }
        if let Some(freq_penalty) = request.frequency_penalty {
            body["frequency_penalty"] = serde_json::json!(freq_penalty);
        }
        if let Some(pres_penalty) = request.presence_penalty {
            body["presence_penalty"] = serde_json::json!(pres_penalty);
        }
        if let Some(level) = normalized_thinking_level(request.thinking_level.as_deref()) {
            if level != "off" && supports_openai_reasoning_effort(deployment) {
                body["reasoning_effort"] = serde_json::json!(level);
            }
        }

        let resp = client
            .post(&url)
            .header("api-key", &self.api_key)
            .header("Content-Type", "application/json")
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| if e.is_timeout() { ProviderError::Timeout } else { ProviderError::Api(e.to_string()) })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if resp.status().as_u16() == 401 {
            return Err(ProviderError::Auth("invalid API key".into()));
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("choices")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usage").map(|u| TokenUsage {
            prompt_tokens: u.get("prompt_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("completion_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        Ok(CompletionResponse {
            text,
            usage,
            model_used: deployment.to_string(),
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

// --- Google AI (Gemini, generativelanguage API)
pub struct GoogleAIProvider {
    api_key: String,
    base_url: String,
}

impl GoogleAIProvider {
    pub fn new(api_key: Option<String>, base_url: Option<String>) -> Self {
        Self {
            api_key: api_key.unwrap_or_default(),
            base_url: base_url
                .unwrap_or_else(|| "https://generativelanguage.googleapis.com".into())
                .trim_end_matches('/')
                .to_string(),
        }
    }
}

#[async_trait]
impl LLMProvider for GoogleAIProvider {
    fn name(&self) -> &str {
        "google"
    }
    fn is_available(&self) -> bool {
        !self.api_key.is_empty()
    }
    fn is_local(&self) -> bool {
        false
    }
    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        if self.api_key.is_empty() {
            return Err(ProviderError::Auth("missing API key".into()));
        }
        let model = model_override.unwrap_or("gemini-1.5-flash");
        let client = reqwest::Client::new();
        let url = format!("{}/v1beta/models/{}:generateContent?key={}", self.base_url, model, self.api_key);
        let prompt = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
            _ => request.prompt.clone(),
        };

        // Build generation config with all supported parameters.
        let mut generation_config = serde_json::json!({
            "maxOutputTokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7)
        });

        if let Some(top_p) = request.top_p {
            generation_config["topP"] = serde_json::json!(top_p);
        }
        if let Some(top_k) = request.top_k {
            generation_config["topK"] = serde_json::json!(top_k);
        }
        if let Some(level) = normalized_thinking_level(request.thinking_level.as_deref()) {
            if supports_google_thinking(model) {
                let budget = match level {
                    "off" => 0u32,
                    "low" => 512u32,
                    "medium" => 2048u32,
                    "high" => 4096u32,
                    _ => 0u32,
                };
                generation_config["thinkingConfig"] = serde_json::json!({ "thinkingBudget": budget });
            }
        }

        let body = serde_json::json!({
            "contents": [{ "parts": [{ "text": prompt }] }],
            "generationConfig": generation_config
        });
        let resp = client
            .post(&url)
            .header("Content-Type", "application/json")
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| if e.is_timeout() { ProviderError::Timeout } else { ProviderError::Api(e.to_string()) })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("candidates")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|c| c.get("content"))
            .and_then(|c| c.get("parts"))
            .and_then(|p| p.as_array())
            .and_then(|a| a.first())
            .and_then(|p| p.get("text"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usageMetadata").map(|u| TokenUsage {
            prompt_tokens: u.get("promptTokenCount").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("candidatesTokenCount").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        Ok(CompletionResponse {
            text,
            usage,
            model_used: model.to_string(),
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

// --- BitNet (local: llama-server / BitNet inference server, OpenAI-compatible API)
pub struct BitNetProvider {
    base_url: String,
}

impl BitNetProvider {
    pub fn new(base_url: Option<String>) -> Self {
        Self {
            base_url: base_url
                .unwrap_or_else(|| "http://127.0.0.1:8080".into())
                .trim_end_matches('/')
                .to_string(),
        }
    }

    fn chat_completions_url(&self) -> String {
        if self.base_url.ends_with("/v1") {
            format!("{}/chat/completions", self.base_url)
        } else {
            format!("{}/v1/chat/completions", self.base_url)
        }
    }

    async fn complete_async(
        &self,
        request: &CompletionRequest,
        model: &str,
        timeout: Duration,
    ) -> Result<CompletionResponse, ProviderError> {
        let client = reqwest::Client::new();
        let url = self.chat_completions_url();
        let user_content = match &request.image_data_urls {
            Some(urls) if !urls.is_empty() => {
                let mut content = vec![serde_json::json!({ "type": "text", "text": request.prompt })];
                for u in urls {
                    content.push(serde_json::json!({
                        "type": "image_url",
                        "image_url": { "url": u }
                    }));
                }
                serde_json::Value::Array(content)
            }
            _ => serde_json::json!(request.prompt),
        };
        let messages = match &request.system_prompt {
            Some(s) if !s.trim().is_empty() => serde_json::json!([
                { "role": "system", "content": s.trim_end() },
                { "role": "user", "content": user_content }
            ]),
            _ => serde_json::json!([{ "role": "user", "content": user_content }]),
        };

        // Build request body with all supported OpenAI-compatible parameters.
        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7),
            "stream": false
        });

        if let Some(top_p) = request.top_p {
            body["top_p"] = serde_json::json!(top_p);
        }
        if let Some(top_k) = request.top_k {
            body["top_k"] = serde_json::json!(top_k);
        }
        if let Some(freq_penalty) = request.frequency_penalty {
            body["frequency_penalty"] = serde_json::json!(freq_penalty);
        }
        if let Some(pres_penalty) = request.presence_penalty {
            body["presence_penalty"] = serde_json::json!(pres_penalty);
        }
        if let Some(repeat_penalty) = request.repeat_penalty {
            body["repeat_penalty"] = serde_json::json!(repeat_penalty);
        }
        if let Some(num_ctx) = request.num_ctx {
            body["num_ctx"] = serde_json::json!(num_ctx);
        }

        let resp = client
            .post(&url)
            .header("Content-Type", "application/json")
            .json(&body)
            .timeout(timeout)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    ProviderError::Timeout
                } else {
                    ProviderError::Api(e.to_string())
                }
            })?;
        if resp.status().as_u16() == 429 {
            return Err(ProviderError::RateLimit);
        }
        if !resp.status().is_success() {
            let status = resp.status();
            let err_body = resp.text().await.unwrap_or_default();
            return Err(ProviderError::Api(format!("{} {}", status, err_body)));
        }
        let json: serde_json::Value = resp.json().await.map_err(|e| ProviderError::Api(e.to_string()))?;
        let text = json
            .get("choices")
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .and_then(|c| c.get("message"))
            .and_then(|m| m.get("content"))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let usage = json.get("usage").map(|u| TokenUsage {
            prompt_tokens: u.get("prompt_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
            completion_tokens: u.get("completion_tokens").and_then(|v| v.as_u64()).unwrap_or(0),
        });
        let model_used = json.get("model").and_then(|v| v.as_str()).unwrap_or(model).to_string();
        Ok(CompletionResponse {
            text,
            usage,
            model_used,
            cost_usd: None,
            thinking: None,
            done_reason: None,
            eval_count: None,
            total_duration_ns: None,
        })
    }
}

#[async_trait]
impl LLMProvider for BitNetProvider {
    fn name(&self) -> &str {
        "bitnet"
    }

    fn is_available(&self) -> bool {
        let client = match reqwest::blocking::Client::builder()
            .timeout(Duration::from_secs(2))
            .build()
        {
            Ok(c) => c,
            Err(_) => return false,
        };
        // Try GET on base URL or /v1/models; many llama.cpp servers respond to root or models
        let models_url = format!("{}/v1/models", self.base_url);
        let urls = [
            self.base_url.as_str(),
            models_url.as_str(),
        ];
        for u in &urls {
            if client.get(*u).send().is_ok() {
                return true;
            }
        }
        false
    }

    fn is_local(&self) -> bool {
        true
    }

    fn supports_streaming(&self) -> bool {
        false
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        timeout: Duration,
        model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        let model = model_override.unwrap_or("default");
        self.complete_async(request, model, timeout).await
    }
}

// --- Akasha Core (local model: embedded LLM when available, else placeholder)
pub struct AkashaCoreProvider;

impl AkashaCoreProvider {
    pub fn new() -> Self {
        Self
    }
}

/// Placeholder when no embedded model is available (spec 34: messages utiles, liens init/paths/doc).
fn placeholder_response(prompt_len: usize) -> CompletionResponse {
    let reply = format!(
        "Request received ({} chars). No local LLM available. For full replies: run Ollama (e.g. ollama run llama3) or add providers in llm_router.yaml. Setup: akasha init; paths: akasha paths; see Documentation tab for the guide.",
        prompt_len
    );
    let completion_tokens = reply.split_whitespace().count() as u64;
    CompletionResponse {
        text: reply,
        usage: Some(TokenUsage {
            prompt_tokens: 0,
            completion_tokens,
        }),
        model_used: "core".into(),
        cost_usd: None,
        thinking: None,
        done_reason: None,
        eval_count: None,
        total_duration_ns: None,
    }
}

#[async_trait]
impl LLMProvider for AkashaCoreProvider {
    fn name(&self) -> &str {
        "akasha_core"
    }

    fn is_available(&self) -> bool {
        true
    }

    fn is_local(&self) -> bool {
        true
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        _timeout: Duration,
        _model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        #[cfg(feature = "embedded")]
        {
            if akasha_embedded_llm::EmbeddedLlm::is_available() {
                let prompt = match &request.system_prompt {
                    Some(s) if !s.is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
                    _ => request.prompt.clone(),
                };
                let max_tokens = request.max_tokens.map(|u| u as usize);
                let temperature = request.temperature.map(|f| f as f64);
                match tokio::task::spawn_blocking(move || {
                    let llm = akasha_embedded_llm::EmbeddedLlm::new();
                    llm.complete(&prompt, max_tokens, temperature)
                })
                .await
                {
                    Ok(Ok(text)) => {
                        let completion_tokens = text.split_whitespace().count() as u64;
                        return Ok(CompletionResponse {
                            text,
                            usage: Some(TokenUsage {
                                prompt_tokens: 0,
                                completion_tokens,
                            }),
                            model_used: "core".into(),
                            cost_usd: None,
                            thinking: None,
                            done_reason: None,
                            eval_count: None,
                            total_duration_ns: None,
                        });
                    }
                    Ok(Err(e)) => {
                        warn!(error = ?e, "AkashaCoreProvider embedded LLM failed to complete prompt; falling back to placeholder response");
                    }
                    Err(join_err) => {
                        warn!(error = ?join_err, "AkashaCoreProvider spawn_blocking for embedded LLM failed; falling back to placeholder response");
                    }
                }
            }
        }
        Ok(placeholder_response(request.prompt.len()))
    }
}

// --- Akasha Embedded (explicit embedded model provider for llm_router; same backend as akasha_core when feature "embedded")
/// Provider name: `akasha_embedded`. Use in llm_router.yaml to route a task type to the embedded model (Qwen3 0.6B or Baguettotron via AKASHA_EMBEDDED_MODEL).
pub struct AkashaEmbeddedProvider;

impl AkashaEmbeddedProvider {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait]
impl LLMProvider for AkashaEmbeddedProvider {
    fn name(&self) -> &str {
        "akasha_embedded"
    }

    fn is_available(&self) -> bool {
        #[cfg(feature = "embedded")]
        return akasha_embedded_llm::EmbeddedLlm::is_available();
        #[cfg(not(feature = "embedded"))]
        false
    }

    fn is_local(&self) -> bool {
        true
    }

    fn supports_streaming(&self) -> bool {
        #[cfg(feature = "embedded")]
        return akasha_embedded_llm::EmbeddedLlm::is_available();
        #[cfg(not(feature = "embedded"))]
        false
    }

    async fn complete(
        &self,
        request: &CompletionRequest,
        _timeout: Duration,
        _model_override: Option<&str>,
    ) -> Result<CompletionResponse, ProviderError> {
        #[cfg(feature = "embedded")]
        {
            if akasha_embedded_llm::EmbeddedLlm::is_available() {
                let prompt = match &request.system_prompt {
                    Some(s) if !s.is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
                    _ => request.prompt.clone(),
                };
                let max_tokens = request.max_tokens.map(|u| u as usize);
                let temperature = request.temperature.map(|f| f as f64);
                match tokio::task::spawn_blocking(move || {
                    let llm = akasha_embedded_llm::EmbeddedLlm::new();
                    llm.complete(&prompt, max_tokens, temperature)
                })
                .await
                {
                    Ok(Ok(text)) => {
                        let completion_tokens = text.split_whitespace().count() as u64;
                        return Ok(CompletionResponse {
                            text,
                            usage: Some(TokenUsage {
                                prompt_tokens: 0,
                                completion_tokens,
                            }),
                            model_used: "embedded".into(),
                            cost_usd: None,
                            thinking: None,
                            done_reason: None,
                            eval_count: None,
                            total_duration_ns: None,
                        });
                    }
                    Ok(Err(e)) => return Err(ProviderError::Api(e.to_string())),
                    Err(e) => return Err(ProviderError::Api(format!("spawn: {}", e))),
                }
            }
        }
        let _ = request;
        Err(ProviderError::Unavailable)
    }

    async fn complete_stream(
        &self,
        request: &CompletionRequest,
        _timeout: Duration,
        _model_override: Option<&str>,
        chunk_tx: std::sync::mpsc::Sender<String>,
    ) -> Result<CompletionResponse, ProviderError> {
        #[cfg(feature = "embedded")]
        {
            if !akasha_embedded_llm::EmbeddedLlm::is_available() {
                return Err(ProviderError::Unavailable);
            }
            let prompt = match &request.system_prompt {
                Some(s) if !s.is_empty() => format!("{}\n\n{}", s.trim_end(), request.prompt),
                _ => request.prompt.clone(),
            };
            let max_tokens = request.max_tokens.map(|u| u as usize);
            let temperature = request.temperature.map(|f| f as f64);
            match tokio::task::spawn_blocking(move || {
                let llm = akasha_embedded_llm::EmbeddedLlm::new();
                llm.complete_stream(&prompt, max_tokens, temperature, move |chunk| {
                    let _ = chunk_tx.send(chunk.to_string());
                })
            })
            .await
            {
                Ok(Ok(text)) => {
                    let completion_tokens = text.split_whitespace().count() as u64;
                    Ok(CompletionResponse {
                        text,
                        usage: Some(TokenUsage {
                            prompt_tokens: 0,
                            completion_tokens,
                        }),
                        model_used: "embedded".into(),
                        cost_usd: None,
                        thinking: None,
                        done_reason: None,
                        eval_count: None,
                        total_duration_ns: None,
                    })
                }
                Ok(Err(e)) => Err(ProviderError::Api(e.to_string())),
                Err(e) => Err(ProviderError::Api(format!("spawn: {}", e))),
            }
        }
        #[cfg(not(feature = "embedded"))]
        {
            let _ = (request, chunk_tx);
            Err(ProviderError::Unavailable)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn ollama_provider_name_and_local() {
        let p = OllamaProvider::new(None);
        assert_eq!(p.name(), "ollama");
        assert!(p.is_local());
    }

    #[test]
    fn ollama_provider_is_available_no_panic() {
        let p = OllamaProvider::new(None);
        let _ = p.is_available();
    }

    #[test]
    fn akasha_embedded_provider_name_and_local() {
        let p = AkashaEmbeddedProvider::new();
        assert_eq!(p.name(), "akasha_embedded");
        assert!(p.is_local());
    }

    #[test]
    fn akasha_embedded_provider_availability_matches_embedded_llm_when_feature_enabled() {
        let p = AkashaEmbeddedProvider::new();
        #[cfg(feature = "embedded")]
        assert_eq!(
            p.is_available(),
            akasha_embedded_llm::EmbeddedLlm::is_available(),
            "AkashaEmbeddedProvider.is_available() should match EmbeddedLlm::is_available() when feature embedded is on"
        );
        #[cfg(not(feature = "embedded"))]
        assert!(!p.is_available());
    }

    #[tokio::test]
    async fn akasha_embedded_provider_complete_when_unavailable_returns_unavailable() {
        let p = AkashaEmbeddedProvider::new();
        if p.is_available() {
            return;
        }
        let req = CompletionRequest {
            prompt: "Hi".into(),
            max_tokens: Some(10),
            temperature: Some(0.0),
            thinking_level: None,
            preferred_task_type: None,
            system_prompt: None,
            image_data_urls: None,
            top_p: None,
            top_k: None,
            frequency_penalty: None,
            presence_penalty: None,
            repeat_penalty: None,
            num_ctx: None,
            num_gpu: None,
        };
        let r = p.complete(&req, Duration::from_secs(5), None).await;
        assert!(r.is_err());
        assert!(matches!(r.unwrap_err(), ProviderError::Unavailable));
    }

    #[test]
    fn azure_provider_name_and_not_local() {
        let p = AzureOpenAIProvider::new(None, None);
        assert_eq!(p.name(), "azure_openai");
        assert!(!p.is_local());
    }

    #[test]
    fn azure_provider_unavailable_with_empty_api_key() {
        let p = AzureOpenAIProvider::new(None, Some("https://myresource.openai.azure.com".into()));
        assert!(!p.is_available(), "Azure provider must be unavailable when api_key is empty");
    }

    #[test]
    fn azure_provider_available_with_api_key_and_base_url() {
        let p = AzureOpenAIProvider::new(
            Some("sk-test-key".into()),
            Some("https://myresource.openai.azure.com".into()),
        );
        assert!(p.is_available(), "Azure provider must be available when both api_key and base_url are set");
    }

    #[test]
    fn azure_provider_default_max_tokens_is_4096() {
        // Verify the Azure provider builds request bodies with max_tokens=4096 when not specified,
        // consistent with all other OpenAI-compatible providers (prevents unexpected truncation).
        // This mirrors the actual body construction in AzureOpenAIProvider::complete().
        let request = CompletionRequest {
            prompt: "test".into(),
            max_tokens: None, // No override → must use the default
            temperature: None,
            top_p: None,
            top_k: None,
            frequency_penalty: None,
            presence_penalty: None,
            repeat_penalty: None,
            num_ctx: None,
            num_gpu: None,
            thinking_level: None,
            preferred_task_type: None,
            system_prompt: None,
            image_data_urls: None,
        };
        // Construct the request body the same way AzureOpenAIProvider::complete() does,
        // to verify the default is 4096 and not the old 1024.
        let body = serde_json::json!({
            "messages": [{ "role": "user", "content": request.prompt }],
            "max_tokens": request.max_tokens.unwrap_or(4096),
            "temperature": request.temperature.unwrap_or(0.7)
        });
        assert_eq!(
            body["max_tokens"].as_u64(),
            Some(4096),
            "Azure request body max_tokens must default to 4096, not 1024"
        );
    }
}
