# Build BitNet llama-server (for testing Akasha BitNet provider).
# Usage: .\bitnet-build.ps1 [-BitNetDir "C:\path\to\BitNet"]
#   BitNetDir: where to clone/build BitNet (default: ..\BitNet relative to script).
# Prereqs: Git, CMake, and Clang (BitNet does not build with MSVC).
#   - Install Visual Studio 2022 with "Desktop development with C++", "C++ Clang compiler for Windows", and "MSBuild support for LLVM (clang-cl)".
#   - Run from "Developer PowerShell for VS 2022" (or after VsDevCmd.bat) so clang is in PATH.
# After build: see spec/runbooks/03_bitnet_server_setup.md to download a model and run the server.

param(
    [string] $BitNetDir = ""
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir
if (-not $BitNetDir) { $BitNetDir = Join-Path $ParentDir "BitNet" }

# BitNet requires Clang or GCC (not MSVC). On Windows we must use Clang.
$clangExe = Get-Command clang -ErrorAction SilentlyContinue
if (-not $clangExe) {
    Write-Host "ERROR: BitNet requires Clang (or GCC). CMake will fail with MSVC." -ForegroundColor Red
    Write-Host ""
    Write-Host "On Windows, install Clang via Visual Studio Installer:" -ForegroundColor Yellow
    Write-Host "  1. Open 'Visual Studio Installer'"
    Write-Host "  2. Modify VS 2022 -> Individual components"
    Write-Host "  3. Search for 'Clang' and enable:"
    Write-Host "     - C++ Clang compiler for Windows"
    Write-Host "     - MSBuild support for LLVM (clang-cl)"
    Write-Host "  4. Close and reopen 'Developer PowerShell for VS 2022', then run this script again."
    Write-Host ""
    Write-Host "Alternatively install LLVM from https://releases.llvm.org/ and add its bin/ to PATH."
    exit 1
}
Write-Host "Using Clang: $($clangExe.Source)"

if (Test-Path $BitNetDir) {
    if (-not (Test-Path (Join-Path $BitNetDir "CMakeLists.txt"))) {
        Write-Error "Directory exists but is not a BitNet repo (no CMakeLists.txt): $BitNetDir"
    }
    Write-Host "Using existing BitNet at $BitNetDir"
    Push-Location $BitNetDir
    git submodule update --init --recursive
    Pop-Location
} else {
    Write-Host "Cloning BitNet into $BitNetDir ..."
    git clone --recursive https://github.com/microsoft/BitNet.git $BitNetDir
}

Push-Location $BitNetDir
$BuildDir = "build"

# BitNet requires include/bitnet-lut-kernels.h to be generated before CMake (see setup_env.py gen_code()).
# On x86_64 we use codegen_tl2.py; the header is generated by Python scripts, not shipped in the repo.
$includeHeader = Join-Path $BitNetDir "include\bitnet-lut-kernels.h"
if (-not (Test-Path $includeHeader)) {
    Write-Host "Generating include/bitnet-lut-kernels.h (required before CMake) ..."
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) {
        Write-Error "Python is required to generate bitnet-lut-kernels.h. Install Python 3.9+ and run this script again, or run from BitNet repo: python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s"
    }
    # x86_64: use codegen_tl2 with params for BitNet 2B/3B (same as setup_env.py for BitNet-b1.58-2B-4T)
    & python utils/codegen_tl2.py --model bitnet_b1_58-3B --BM 160,320,320 --BK 96,96,96 --bm 32,32,32
    if (-not (Test-Path $includeHeader)) {
        Write-Error "Codegen did not create include/bitnet-lut-kernels.h. Try running from BitNet repo: python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s"
    }
}

# Workaround: BitNet src uses non-const pointer (fails with -Wcast-qual). Patch so build succeeds on Windows Clang.
$madCpp = Join-Path $BitNetDir "src\ggml-bitnet-mad.cpp"
if (Test-Path $madCpp) {
    $content = Get-Content -Path $madCpp -Raw
    if ($content -match '(\s+)int8_t \* y_col = y \+ col \* by;') {
        $content = $content -replace '(\s+)int8_t \* y_col = y \+ col \* by;', '$1const int8_t * y_col = y + col * by;'
        Set-Content -Path $madCpp -Value $content -NoNewline
    }
}
# Workaround: ggml does not add -mavxvnni for x86/Clang; _mm256_dpbusd_epi32 stays undeclared. Inject into ARCH_FLAGS.
$ggmlCmake = Join-Path $BitNetDir "3rdparty\llama.cpp\ggml\src\CMakeLists.txt"
if (Test-Path $ggmlCmake) {
    $gc = Get-Content -Path $ggmlCmake -Raw
    if ($gc -notmatch 'ARCH_FLAGS -mavxvnni') {
        $gc = $gc -replace '(list\(APPEND ARCH_FLAGS -mavx2\))\r?\n(\s+endif\(\))\r?\n(\s+if \(GGML_AVX512\))', "`$1`n`$2`n        list(APPEND ARCH_FLAGS -mavxvnni)  # Akasha: _mm256_dpbusd_epi32 on Windows Clang`n`$3"
        if ($gc -match 'ARCH_FLAGS -mavxvnni') { Set-Content -Path $ggmlCmake -Value $gc -NoNewline }
    }
}
# Workaround: Windows Clang < 16 does not declare _mm256_dpbusd_epi32 in headers; force fallback path.
$avxVnniPatch = '#if defined(__AVXVNNI__) || (defined(__AVX512VNNI__) && defined(__AVX512VL__))'
$avxVnniPatched = '#if (defined(__AVXVNNI__) || (defined(__AVX512VNNI__) && defined(__AVX512VL__))) && !(defined(_WIN32) && defined(__clang__) && __clang_major__ < 16)'
foreach ($f in @("3rdparty\llama.cpp\ggml\src\ggml-aarch64.c", "3rdparty\llama.cpp\ggml\src\ggml-quants.c")) {
    $path = Join-Path $BitNetDir $f
    if (Test-Path $path) {
        $c = Get-Content -Path $path -Raw
        if ($c -match [regex]::Escape($avxVnniPatch) -and $c -notmatch '__clang_major__ < 16') {
            ($c -replace [regex]::Escape($avxVnniPatch), $avxVnniPatched) | Set-Content -Path $path -NoNewline
        }
    }
}

# Remove stale build so CMake reconfigures with Clang (in case a previous MSVC config existed)
if (Test-Path $BuildDir) {
    Write-Host "Removing previous build directory to force Clang configuration..."
    Remove-Item -Recurse -Force $BuildDir
}

Write-Host "Configuring (Release, x64, Clang) ..."
# BitNet requires Clang or GCC. Use Ninja + Clang, or VS generator with -T ClangCL.
# GGML_LLAMAFILE=OFF avoids sgemm.cpp which uses _mm256_dpbusd_epi32 (AVX-VNNI) not declared in Clang 15 on Windows.
# -mavxvnni ensures the intrinsic is declared in ggml-quants.c / ggml-aarch64.c when the CPU supports it.
# GGML_OPENMP=OFF avoids undefined OpenMP symbols (___kmpc_*, _omp_*) when linking with Clang/lld-link on Windows.
$hasNinja = Get-Command ninja -ErrorAction SilentlyContinue
$avxFlags = "-march=native -mavxvnni"
if ($hasNinja) {
    cmake -S . -B $BuildDir -G Ninja -DCMAKE_BUILD_TYPE=Release `
        -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ `
        -DGGML_LLAMAFILE=OFF -DGGML_OPENMP=OFF `
        -DCMAKE_C_FLAGS=$avxFlags -DCMAKE_CXX_FLAGS=$avxFlags
} else {
    cmake -S . -B $BuildDir -G "Visual Studio 17 2022" -A x64 -T ClangCL -DCMAKE_BUILD_TYPE=Release `
        -DGGML_LLAMAFILE=OFF -DGGML_OPENMP=OFF `
        -DCMAKE_C_FLAGS=$avxFlags -DCMAKE_CXX_FLAGS=$avxFlags
}

Write-Host "Building ..."
if ($hasNinja) {
    cmake --build $BuildDir -j
} else {
    cmake --build $BuildDir --config Release
}

# Windows: executable is often in build/bin/Release/llama-server.exe
$ExeRelease = Join-Path $BuildDir "bin\Release\llama-server.exe"
$ExeBin = Join-Path $BuildDir "bin\llama-server.exe"
$Exe = $null
if (Test-Path $ExeRelease) { $Exe = $ExeRelease }
elseif (Test-Path $ExeBin) { $Exe = $ExeBin }

Pop-Location

if ($Exe) {
    $FullExe = Join-Path $BitNetDir $Exe
    Write-Host "Build OK. Executable: $FullExe"
    Write-Host ""
    Write-Host "Next steps:"
    Write-Host "  1) Download a model, e.g.:"
    Write-Host "     huggingface-cli download microsoft/BitNet-b1.58-2B-4T-gguf --local-dir $BitNetDir\models\BitNet-b1.58-2B-4T"
    Write-Host "  2) Start the server:"
    Write-Host "     $FullExe -m $BitNetDir\models\BitNet-b1.58-2B-4T\ggml-model-i2_s.gguf --host 127.0.0.1 --port 8080 -c 2048 -t 2 -cb"
    Write-Host "  3) In llm_router.yaml set provider bitnet with base_url http://127.0.0.1:8080 and use task_types.conversation.primary.provider: bitnet"
    Write-Host ""
    Write-Host "See spec/runbooks/03_bitnet_server_setup.md for full runbook."
} else {
    Write-Error "Executable not found (checked bin\Release\llama-server.exe and bin\llama-server.exe)."
}
